# Generated by Django 4.1.4 on 2022-12-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fotos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artista",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fotos.categoria_artista",
            ),
        ),
        migrations.AlterField(
            model_name="artista",
            name="descripcion",
            field=models.TextField(),
        ),
    ]
