# Generated by Django 4.1.4 on 2022-12-14 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fotos", "0003_categoria_artista_imagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria_proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="categoria_artista",
            name="categoria_proyecto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fotos.categoria_proyecto",
            ),
        ),
    ]
